/**
 * This class is generated by jOOQ
 */
package com.serinus.loto.model.jooq.tables.daos


import com.serinus.loto.model.jooq.tables.TmCombinationPart
import com.serinus.loto.model.jooq.tables.records.TmCombinationPartRecord

import java.lang.Integer
import java.lang.Short
import java.lang.String
import java.time.LocalDateTime
import java.util.List

import javax.annotation.Generated

import org.jooq.Configuration
import org.jooq.impl.DAOImpl

import scala.Array


/**
 * This class is generated by jOOQ.
 */
@Generated(
  value = Array(
    "http://www.jooq.org",
    "jOOQ version:3.8.6"
  ),
  comments = "This class is generated by jOOQ"
)
class TmCombinationPartDao(configuration : Configuration) extends DAOImpl[TmCombinationPartRecord, com.serinus.loto.model.pojos.TmCombinationPart, Integer](TmCombinationPart.TM_COMBINATION_PART, classOf[com.serinus.loto.model.pojos.TmCombinationPart], configuration) {

  /**
   * Create a new TmCombinationPartDao without any configuration
   */
  def this() = {
    this(null)
  }

  override protected def getId(o : com.serinus.loto.model.pojos.TmCombinationPart) : Integer = {
    o.getId
  }

  /**
   * Fetch records that have <code>id IN (values)</code>
   */
  def fetchById(values : Integer*) : List[com.serinus.loto.model.pojos.TmCombinationPart] = {
    fetch(TmCombinationPart.TM_COMBINATION_PART.ID, values:_*)
  }

  /**
   * Fetch a unique record that has <code>id = value</code>
   */
  def fetchOneById(value : Integer) : com.serinus.loto.model.pojos.TmCombinationPart = {
    fetchOne(TmCombinationPart.TM_COMBINATION_PART.ID, value)
  }

  /**
   * Fetch records that have <code>lottery_id IN (values)</code>
   */
  def fetchByLotteryId(values : Integer*) : List[com.serinus.loto.model.pojos.TmCombinationPart] = {
    fetch(TmCombinationPart.TM_COMBINATION_PART.LOTTERY_ID, values:_*)
  }

  /**
   * Fetch records that have <code>part_number IN (values)</code>
   */
  def fetchByPartNumber(values : Short*) : List[com.serinus.loto.model.pojos.TmCombinationPart] = {
    fetch(TmCombinationPart.TM_COMBINATION_PART.PART_NUMBER, values:_*)
  }

  /**
   * Fetch records that have <code>name IN (values)</code>
   */
  def fetchByName(values : String*) : List[com.serinus.loto.model.pojos.TmCombinationPart] = {
    fetch(TmCombinationPart.TM_COMBINATION_PART.NAME, values:_*)
  }

  /**
   * Fetch records that have <code>num_values IN (values)</code>
   */
  def fetchByNumValues(values : Short*) : List[com.serinus.loto.model.pojos.TmCombinationPart] = {
    fetch(TmCombinationPart.TM_COMBINATION_PART.NUM_VALUES, values:_*)
  }

  /**
   * Fetch records that have <code>created IN (values)</code>
   */
  def fetchByCreated(values : LocalDateTime*) : List[com.serinus.loto.model.pojos.TmCombinationPart] = {
    fetch(TmCombinationPart.TM_COMBINATION_PART.CREATED, values:_*)
  }

  /**
   * Fetch records that have <code>modified IN (values)</code>
   */
  def fetchByModified(values : LocalDateTime*) : List[com.serinus.loto.model.pojos.TmCombinationPart] = {
    fetch(TmCombinationPart.TM_COMBINATION_PART.MODIFIED, values:_*)
  }
}
