/**
 * This class is generated by jOOQ
 */
package com.serinus.loto.model.jooq.tables.daos


import com.serinus.loto.model.jooq.tables.TwResult
import com.serinus.loto.model.jooq.tables.records.TwResultRecord

import java.lang.Integer
import java.lang.String
import java.time.LocalDate
import java.time.LocalDateTime
import java.util.List

import javax.annotation.Generated

import org.jooq.Configuration
import org.jooq.impl.DAOImpl

import scala.Array


/**
 * This class is generated by jOOQ.
 */
@Generated(
  value = Array(
    "http://www.jooq.org",
    "jOOQ version:3.8.6"
  ),
  comments = "This class is generated by jOOQ"
)
class TwResultDao(configuration : Configuration) extends DAOImpl[TwResultRecord, com.serinus.loto.model.pojos.TwResult, Integer](TwResult.TW_RESULT, classOf[com.serinus.loto.model.pojos.TwResult], configuration) {

  /**
   * Create a new TwResultDao without any configuration
   */
  def this() = {
    this(null)
  }

  override protected def getId(o : com.serinus.loto.model.pojos.TwResult) : Integer = {
    o.getId
  }

  /**
   * Fetch records that have <code>id IN (values)</code>
   */
  def fetchById(values : Integer*) : List[com.serinus.loto.model.pojos.TwResult] = {
    fetch(TwResult.TW_RESULT.ID, values:_*)
  }

  /**
   * Fetch a unique record that has <code>id = value</code>
   */
  def fetchOneById(value : Integer) : com.serinus.loto.model.pojos.TwResult = {
    fetchOne(TwResult.TW_RESULT.ID, value)
  }

  /**
   * Fetch records that have <code>raffle_day IN (values)</code>
   */
  def fetchByRaffleDay(values : LocalDate*) : List[com.serinus.loto.model.pojos.TwResult] = {
    fetch(TwResult.TW_RESULT.RAFFLE_DAY, values:_*)
  }

  /**
   * Fetch records that have <code>combination_part_id IN (values)</code>
   */
  def fetchByCombinationPartId(values : Integer*) : List[com.serinus.loto.model.pojos.TwResult] = {
    fetch(TwResult.TW_RESULT.COMBINATION_PART_ID, values:_*)
  }

  /**
   * Fetch records that have <code>values IN (values)</code>
   */
  def fetchByValues(values : String*) : List[com.serinus.loto.model.pojos.TwResult] = {
    fetch(TwResult.TW_RESULT.VALUES, values:_*)
  }

  /**
   * Fetch records that have <code>created IN (values)</code>
   */
  def fetchByCreated(values : LocalDateTime*) : List[com.serinus.loto.model.pojos.TwResult] = {
    fetch(TwResult.TW_RESULT.CREATED, values:_*)
  }
}
