/**
 * This class is generated by jOOQ
 */
package com.serinus.loto.model.jooq


import com.serinus.loto.model.jooq.tables.TmCombinationPart
import com.serinus.loto.model.jooq.tables.TmLottery
import com.serinus.loto.model.jooq.tables.TwResult
import com.serinus.loto.model.jooq.tables.records.TmCombinationPartRecord
import com.serinus.loto.model.jooq.tables.records.TmLotteryRecord
import com.serinus.loto.model.jooq.tables.records.TwResultRecord

import java.lang.Integer

import javax.annotation.Generated

import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.UniqueKey
import org.jooq.impl.AbstractKeys

import scala.Array


/**
 * A class modelling foreign key relationships between tables of the <code>lottery_schema</code> 
 * schema
 */
@Generated(
  value = Array(
    "http://www.jooq.org",
    "jOOQ version:3.8.6"
  ),
  comments = "This class is generated by jOOQ"
)
object Keys {

  // -------------------------------------------------------------------------
  // IDENTITY definitions
  // -------------------------------------------------------------------------

  val IDENTITY_TM_COMBINATION_PART = Identities0.IDENTITY_TM_COMBINATION_PART
  val IDENTITY_TM_LOTTERY = Identities0.IDENTITY_TM_LOTTERY
  val IDENTITY_TW_RESULT = Identities0.IDENTITY_TW_RESULT

  // -------------------------------------------------------------------------
  // UNIQUE and PRIMARY KEY definitions
  // -------------------------------------------------------------------------

  val TM_COMBINATION_PART_PK = UniqueKeys0.TM_COMBINATION_PART_PK
  val TM_COMBINATION_PART_UK = UniqueKeys0.TM_COMBINATION_PART_UK
  val TM_LOTTERY_PK = UniqueKeys0.TM_LOTTERY_PK
  val TW_RESULT_PK = UniqueKeys0.TW_RESULT_PK
  val TW_RESULT_UK = UniqueKeys0.TW_RESULT_UK

  // -------------------------------------------------------------------------
  // FOREIGN KEY definitions
  // -------------------------------------------------------------------------

  val TM_COMBINATION_PART__TM_COMBINATION_PART_TM_LOTTERY_FK = ForeignKeys0.TM_COMBINATION_PART__TM_COMBINATION_PART_TM_LOTTERY_FK
  val TW_RESULT__TW_RESULT_TM_COMBINATION_PART_FK = ForeignKeys0.TW_RESULT__TW_RESULT_TM_COMBINATION_PART_FK

  // -------------------------------------------------------------------------
  // [#1459] distribute members to avoid static initialisers > 64kb
  // -------------------------------------------------------------------------

  private object Identities0 extends AbstractKeys {
    val IDENTITY_TM_COMBINATION_PART : Identity[TmCombinationPartRecord, Integer] = AbstractKeys.createIdentity(TmCombinationPart.TM_COMBINATION_PART, TmCombinationPart.TM_COMBINATION_PART.ID)
    val IDENTITY_TM_LOTTERY : Identity[TmLotteryRecord, Integer] = AbstractKeys.createIdentity(TmLottery.TM_LOTTERY, TmLottery.TM_LOTTERY.ID)
    val IDENTITY_TW_RESULT : Identity[TwResultRecord, Integer] = AbstractKeys.createIdentity(TwResult.TW_RESULT, TwResult.TW_RESULT.ID)
  }

  private object UniqueKeys0 extends AbstractKeys {
    val TM_COMBINATION_PART_PK : UniqueKey[TmCombinationPartRecord] = AbstractKeys.createUniqueKey(TmCombinationPart.TM_COMBINATION_PART, "tm_combination_part_pk", TmCombinationPart.TM_COMBINATION_PART.ID)
    val TM_COMBINATION_PART_UK : UniqueKey[TmCombinationPartRecord] = AbstractKeys.createUniqueKey(TmCombinationPart.TM_COMBINATION_PART, "tm_combination_part_uk", TmCombinationPart.TM_COMBINATION_PART.LOTTERY_ID, TmCombinationPart.TM_COMBINATION_PART.PART_NUMBER)
    val TM_LOTTERY_PK : UniqueKey[TmLotteryRecord] = AbstractKeys.createUniqueKey(TmLottery.TM_LOTTERY, "tm_lottery_pk", TmLottery.TM_LOTTERY.ID)
    val TW_RESULT_PK : UniqueKey[TwResultRecord] = AbstractKeys.createUniqueKey(TwResult.TW_RESULT, "tw_result_pk", TwResult.TW_RESULT.ID)
    val TW_RESULT_UK : UniqueKey[TwResultRecord] = AbstractKeys.createUniqueKey(TwResult.TW_RESULT, "tw_result_uk", TwResult.TW_RESULT.RAFFLE_DAY, TwResult.TW_RESULT.COMBINATION_PART_ID)
  }

  private object ForeignKeys0 extends AbstractKeys {
    val TM_COMBINATION_PART__TM_COMBINATION_PART_TM_LOTTERY_FK : ForeignKey[TmCombinationPartRecord, TmLotteryRecord] = AbstractKeys.createForeignKey(com.serinus.loto.model.jooq.Keys.TM_LOTTERY_PK, TmCombinationPart.TM_COMBINATION_PART, "tm_combination_part__tm_combination_part_tm_lottery_fk", TmCombinationPart.TM_COMBINATION_PART.LOTTERY_ID)
    val TW_RESULT__TW_RESULT_TM_COMBINATION_PART_FK : ForeignKey[TwResultRecord, TmCombinationPartRecord] = AbstractKeys.createForeignKey(com.serinus.loto.model.jooq.Keys.TM_COMBINATION_PART_PK, TwResult.TW_RESULT, "tw_result__tw_result_tm_combination_part_fk", TwResult.TW_RESULT.COMBINATION_PART_ID)
  }
}
