/**
 * This class is generated by jOOQ
 */
package com.serinus.loto.model.jooq


import com.serinus.loto.model.jooq.routines.UpdateModifiedColumn

import java.lang.Object

import javax.annotation.Generated

import org.jooq.Configuration
import org.jooq.Field

import scala.Array


/**
 * Convenience access to all stored procedures and functions in lottery_schema
 */
@Generated(
  value = Array(
    "http://www.jooq.org",
    "jOOQ version:3.8.6"
  ),
  comments = "This class is generated by jOOQ"
)
object Routines {

  /**
   * Call <code>lottery_schema.update_modified_column</code>
   */
  def updateModifiedColumn(configuration : Configuration) : Object = {
    val f = new UpdateModifiedColumn()

    f.execute(configuration)
    f.getReturnValue
  }

  /**
   * Get <code>lottery_schema.update_modified_column</code> as a field.
   */
  def updateModifiedColumn() : Field[Object] = {
    val f = new UpdateModifiedColumn

    return f.asField
  }
}
