/**
 * This class is generated by jOOQ
 */
package com.serinus.loto.model.jooq


import java.lang.Long

import javax.annotation.Generated

import org.jooq.Sequence
import org.jooq.impl.SequenceImpl

import scala.Array


/**
 * Convenience access to all sequences in lottery_schema
 */
@Generated(
  value = Array(
    "http://www.jooq.org",
    "jOOQ version:3.8.6"
  ),
  comments = "This class is generated by jOOQ"
)
object Sequences {

  /**
   * The sequence <code>lottery_schema.tm_combination_part_id_seq</code>
   */
  val TM_COMBINATION_PART_ID_SEQ : Sequence[Long] = new SequenceImpl[Long]("tm_combination_part_id_seq", LotterySchema.LOTTERY_SCHEMA, org.jooq.impl.SQLDataType.BIGINT.nullable(false))

  /**
   * The sequence <code>lottery_schema.tm_lottery_id_seq</code>
   */
  val TM_LOTTERY_ID_SEQ : Sequence[Long] = new SequenceImpl[Long]("tm_lottery_id_seq", LotterySchema.LOTTERY_SCHEMA, org.jooq.impl.SQLDataType.BIGINT.nullable(false))

  /**
   * The sequence <code>lottery_schema.tw_result_id_seq</code>
   */
  val TW_RESULT_ID_SEQ : Sequence[Long] = new SequenceImpl[Long]("tw_result_id_seq", LotterySchema.LOTTERY_SCHEMA, org.jooq.impl.SQLDataType.BIGINT.nullable(false))
}
