/**
 * This class is generated by jOOQ
 */
package com.serinus.loto.model.jooq


import com.serinus.loto.model.jooq.tables.TmCombinationPart
import com.serinus.loto.model.jooq.tables.TmLottery
import com.serinus.loto.model.jooq.tables.TwResult

import javax.annotation.Generated

import scala.Array


/**
 * Convenience access to all tables in lottery_schema
 */
@Generated(
  value = Array(
    "http://www.jooq.org",
    "jOOQ version:3.8.6"
  ),
  comments = "This class is generated by jOOQ"
)
object Tables {

  /**
   * The table <code>lottery_schema.tm_combination_part</code>.
   */
  val TM_COMBINATION_PART = com.serinus.loto.model.jooq.tables.TmCombinationPart.TM_COMBINATION_PART

  /**
   * The table <code>lottery_schema.tm_lottery</code>.
   */
  val TM_LOTTERY = com.serinus.loto.model.jooq.tables.TmLottery.TM_LOTTERY

  /**
   * The table <code>lottery_schema.tw_result</code>.
   */
  val TW_RESULT = com.serinus.loto.model.jooq.tables.TwResult.TW_RESULT
}
