/**
 * This class is generated by jOOQ
 */
package com.serinus.loto.model.jooq.routines


import com.serinus.loto.model.jooq.LotterySchema

import java.lang.Object

import javax.annotation.Generated

import org.jooq.Parameter
import org.jooq.impl.AbstractRoutine

import scala.Array


object UpdateModifiedColumn {

  /**
   * The parameter <code>lottery_schema.update_modified_column.RETURN_VALUE</code>.
   */
  val RETURN_VALUE : Parameter[Object] = AbstractRoutine.createParameter("RETURN_VALUE", org.jooq.impl.DefaultDataType.getDefaultDataType("trigger"), false, false)
}

/**
 * This class is generated by jOOQ.
 */
@Generated(
  value = Array(
    "http://www.jooq.org",
    "jOOQ version:3.8.6"
  ),
  comments = "This class is generated by jOOQ"
)
class UpdateModifiedColumn extends AbstractRoutine[Object]("update_modified_column", LotterySchema.LOTTERY_SCHEMA, org.jooq.impl.DefaultDataType.getDefaultDataType("trigger")) {
  {
    setReturnParameter(UpdateModifiedColumn.RETURN_VALUE)
  }
}
