/**
 * This class is generated by jOOQ
 */
package com.serinus.loto.model.jooq.tables.records


import com.serinus.loto.model.jooq.tables.TmCombinationPart

import java.lang.Integer
import java.lang.Short
import java.lang.String
import java.time.LocalDateTime

import javax.annotation.Generated

import org.jooq.Field
import org.jooq.Record1
import org.jooq.Record7
import org.jooq.Row7
import org.jooq.impl.UpdatableRecordImpl

import scala.Array


/**
 * This class is generated by jOOQ.
 */
@Generated(
  value = Array(
    "http://www.jooq.org",
    "jOOQ version:3.8.6"
  ),
  comments = "This class is generated by jOOQ"
)
class TmCombinationPartRecord extends UpdatableRecordImpl[TmCombinationPartRecord](TmCombinationPart.TM_COMBINATION_PART) with Record7[Integer, Integer, Short, String, Short, LocalDateTime, LocalDateTime] {

  /**
   * Setter for <code>lottery_schema.tm_combination_part.id</code>.
   */
  def setId(value : Integer) : Unit = {
    set(0, value)
  }

  /**
   * Getter for <code>lottery_schema.tm_combination_part.id</code>.
   */
  def getId : Integer = {
    val r = get(0)
    if (r == null) null else r.asInstanceOf[Integer]
  }

  /**
   * Setter for <code>lottery_schema.tm_combination_part.lottery_id</code>.
   */
  def setLotteryId(value : Integer) : Unit = {
    set(1, value)
  }

  /**
   * Getter for <code>lottery_schema.tm_combination_part.lottery_id</code>.
   */
  def getLotteryId : Integer = {
    val r = get(1)
    if (r == null) null else r.asInstanceOf[Integer]
  }

  /**
   * Setter for <code>lottery_schema.tm_combination_part.part_number</code>.
   */
  def setPartNumber(value : Short) : Unit = {
    set(2, value)
  }

  /**
   * Getter for <code>lottery_schema.tm_combination_part.part_number</code>.
   */
  def getPartNumber : Short = {
    val r = get(2)
    if (r == null) null else r.asInstanceOf[Short]
  }

  /**
   * Setter for <code>lottery_schema.tm_combination_part.name</code>.
   */
  def setName(value : String) : Unit = {
    set(3, value)
  }

  /**
   * Getter for <code>lottery_schema.tm_combination_part.name</code>.
   */
  def getName : String = {
    val r = get(3)
    if (r == null) null else r.asInstanceOf[String]
  }

  /**
   * Setter for <code>lottery_schema.tm_combination_part.num_values</code>.
   */
  def setNumValues(value : Short) : Unit = {
    set(4, value)
  }

  /**
   * Getter for <code>lottery_schema.tm_combination_part.num_values</code>.
   */
  def getNumValues : Short = {
    val r = get(4)
    if (r == null) null else r.asInstanceOf[Short]
  }

  /**
   * Setter for <code>lottery_schema.tm_combination_part.created</code>.
   */
  def setCreated(value : LocalDateTime) : Unit = {
    set(5, value)
  }

  /**
   * Getter for <code>lottery_schema.tm_combination_part.created</code>.
   */
  def getCreated : LocalDateTime = {
    val r = get(5)
    if (r == null) null else r.asInstanceOf[LocalDateTime]
  }

  /**
   * Setter for <code>lottery_schema.tm_combination_part.modified</code>.
   */
  def setModified(value : LocalDateTime) : Unit = {
    set(6, value)
  }

  /**
   * Getter for <code>lottery_schema.tm_combination_part.modified</code>.
   */
  def getModified : LocalDateTime = {
    val r = get(6)
    if (r == null) null else r.asInstanceOf[LocalDateTime]
  }

  // -------------------------------------------------------------------------
  // Primary key information
  // -------------------------------------------------------------------------
  override def key() : Record1[Integer] = {
    return super.key.asInstanceOf[ Record1[Integer] ]
  }

  // -------------------------------------------------------------------------
  // Record7 type implementation
  // -------------------------------------------------------------------------

  override def fieldsRow : Row7[Integer, Integer, Short, String, Short, LocalDateTime, LocalDateTime] = {
    super.fieldsRow.asInstanceOf[ Row7[Integer, Integer, Short, String, Short, LocalDateTime, LocalDateTime] ]
  }

  override def valuesRow : Row7[Integer, Integer, Short, String, Short, LocalDateTime, LocalDateTime] = {
    super.valuesRow.asInstanceOf[ Row7[Integer, Integer, Short, String, Short, LocalDateTime, LocalDateTime] ]
  }
  override def field1 : Field[Integer] = TmCombinationPart.TM_COMBINATION_PART.ID
  override def field2 : Field[Integer] = TmCombinationPart.TM_COMBINATION_PART.LOTTERY_ID
  override def field3 : Field[Short] = TmCombinationPart.TM_COMBINATION_PART.PART_NUMBER
  override def field4 : Field[String] = TmCombinationPart.TM_COMBINATION_PART.NAME
  override def field5 : Field[Short] = TmCombinationPart.TM_COMBINATION_PART.NUM_VALUES
  override def field6 : Field[LocalDateTime] = TmCombinationPart.TM_COMBINATION_PART.CREATED
  override def field7 : Field[LocalDateTime] = TmCombinationPart.TM_COMBINATION_PART.MODIFIED
  override def value1 : Integer = getId
  override def value2 : Integer = getLotteryId
  override def value3 : Short = getPartNumber
  override def value4 : String = getName
  override def value5 : Short = getNumValues
  override def value6 : LocalDateTime = getCreated
  override def value7 : LocalDateTime = getModified

  override def value1(value : Integer) : TmCombinationPartRecord = {
    setId(value)
    this
  }

  override def value2(value : Integer) : TmCombinationPartRecord = {
    setLotteryId(value)
    this
  }

  override def value3(value : Short) : TmCombinationPartRecord = {
    setPartNumber(value)
    this
  }

  override def value4(value : String) : TmCombinationPartRecord = {
    setName(value)
    this
  }

  override def value5(value : Short) : TmCombinationPartRecord = {
    setNumValues(value)
    this
  }

  override def value6(value : LocalDateTime) : TmCombinationPartRecord = {
    setCreated(value)
    this
  }

  override def value7(value : LocalDateTime) : TmCombinationPartRecord = {
    setModified(value)
    this
  }

  override def values(value1 : Integer, value2 : Integer, value3 : Short, value4 : String, value5 : Short, value6 : LocalDateTime, value7 : LocalDateTime) : TmCombinationPartRecord = {
    this.value1(value1)
    this.value2(value2)
    this.value3(value3)
    this.value4(value4)
    this.value5(value5)
    this.value6(value6)
    this.value7(value7)
    this
  }

  /**
   * Create a detached, initialised TmCombinationPartRecord
   */
  def this(id : Integer, lotteryId : Integer, partNumber : Short, name : String, numValues : Short, created : LocalDateTime, modified : LocalDateTime) = {
    this()

    set(0, id)
    set(1, lotteryId)
    set(2, partNumber)
    set(3, name)
    set(4, numValues)
    set(5, created)
    set(6, modified)
  }
}
