/**
 * This class is generated by jOOQ
 */
package com.serinus.loto.model.jooq.tables.records


import com.serinus.loto.model.jooq.tables.TwResult

import java.lang.Integer
import java.lang.String
import java.time.LocalDate
import java.time.LocalDateTime

import javax.annotation.Generated

import org.jooq.Field
import org.jooq.Record1
import org.jooq.Record5
import org.jooq.Row5
import org.jooq.impl.UpdatableRecordImpl

import scala.Array


/**
 * This class is generated by jOOQ.
 */
@Generated(
  value = Array(
    "http://www.jooq.org",
    "jOOQ version:3.8.6"
  ),
  comments = "This class is generated by jOOQ"
)
class TwResultRecord extends UpdatableRecordImpl[TwResultRecord](TwResult.TW_RESULT) with Record5[Integer, LocalDate, Integer, String, LocalDateTime] {

  /**
   * Setter for <code>lottery_schema.tw_result.id</code>.
   */
  def setId(value : Integer) : Unit = {
    set(0, value)
  }

  /**
   * Getter for <code>lottery_schema.tw_result.id</code>.
   */
  def getId : Integer = {
    val r = get(0)
    if (r == null) null else r.asInstanceOf[Integer]
  }

  /**
   * Setter for <code>lottery_schema.tw_result.raffle_day</code>.
   */
  def setRaffleDay(value : LocalDate) : Unit = {
    set(1, value)
  }

  /**
   * Getter for <code>lottery_schema.tw_result.raffle_day</code>.
   */
  def getRaffleDay : LocalDate = {
    val r = get(1)
    if (r == null) null else r.asInstanceOf[LocalDate]
  }

  /**
   * Setter for <code>lottery_schema.tw_result.combination_part_id</code>.
   */
  def setCombinationPartId(value : Integer) : Unit = {
    set(2, value)
  }

  /**
   * Getter for <code>lottery_schema.tw_result.combination_part_id</code>.
   */
  def getCombinationPartId : Integer = {
    val r = get(2)
    if (r == null) null else r.asInstanceOf[Integer]
  }

  /**
   * Setter for <code>lottery_schema.tw_result.values</code>.
   */
  def setValues(value : String) : Unit = {
    set(3, value)
  }

  /**
   * Getter for <code>lottery_schema.tw_result.values</code>.
   */
  def getValues : String = {
    val r = get(3)
    if (r == null) null else r.asInstanceOf[String]
  }

  /**
   * Setter for <code>lottery_schema.tw_result.created</code>.
   */
  def setCreated(value : LocalDateTime) : Unit = {
    set(4, value)
  }

  /**
   * Getter for <code>lottery_schema.tw_result.created</code>.
   */
  def getCreated : LocalDateTime = {
    val r = get(4)
    if (r == null) null else r.asInstanceOf[LocalDateTime]
  }

  // -------------------------------------------------------------------------
  // Primary key information
  // -------------------------------------------------------------------------
  override def key() : Record1[Integer] = {
    return super.key.asInstanceOf[ Record1[Integer] ]
  }

  // -------------------------------------------------------------------------
  // Record5 type implementation
  // -------------------------------------------------------------------------

  override def fieldsRow : Row5[Integer, LocalDate, Integer, String, LocalDateTime] = {
    super.fieldsRow.asInstanceOf[ Row5[Integer, LocalDate, Integer, String, LocalDateTime] ]
  }

  override def valuesRow : Row5[Integer, LocalDate, Integer, String, LocalDateTime] = {
    super.valuesRow.asInstanceOf[ Row5[Integer, LocalDate, Integer, String, LocalDateTime] ]
  }
  override def field1 : Field[Integer] = TwResult.TW_RESULT.ID
  override def field2 : Field[LocalDate] = TwResult.TW_RESULT.RAFFLE_DAY
  override def field3 : Field[Integer] = TwResult.TW_RESULT.COMBINATION_PART_ID
  override def field4 : Field[String] = TwResult.TW_RESULT.VALUES
  override def field5 : Field[LocalDateTime] = TwResult.TW_RESULT.CREATED
  override def value1 : Integer = getId
  override def value2 : LocalDate = getRaffleDay
  override def value3 : Integer = getCombinationPartId
  override def value4 : String = getValues
  override def value5 : LocalDateTime = getCreated

  override def value1(value : Integer) : TwResultRecord = {
    setId(value)
    this
  }

  override def value2(value : LocalDate) : TwResultRecord = {
    setRaffleDay(value)
    this
  }

  override def value3(value : Integer) : TwResultRecord = {
    setCombinationPartId(value)
    this
  }

  override def value4(value : String) : TwResultRecord = {
    setValues(value)
    this
  }

  override def value5(value : LocalDateTime) : TwResultRecord = {
    setCreated(value)
    this
  }

  override def values(value1 : Integer, value2 : LocalDate, value3 : Integer, value4 : String, value5 : LocalDateTime) : TwResultRecord = {
    this.value1(value1)
    this.value2(value2)
    this.value3(value3)
    this.value4(value4)
    this.value5(value5)
    this
  }

  /**
   * Create a detached, initialised TwResultRecord
   */
  def this(id : Integer, raffleDay : LocalDate, combinationPartId : Integer, values : String, created : LocalDateTime) = {
    this()

    set(0, id)
    set(1, raffleDay)
    set(2, combinationPartId)
    set(3, values)
    set(4, created)
  }
}
