/**
 * This class is generated by jOOQ
 */
package com.serinus.loto.model.pojos


import java.io.Serializable
import java.lang.Integer
import java.lang.Short
import java.lang.String
import java.lang.StringBuilder
import java.time.LocalDateTime

import javax.annotation.Generated

import scala.Array


/**
 * This class is generated by jOOQ.
 */
@Generated(
  value = Array(
    "http://www.jooq.org",
    "jOOQ version:3.8.6"
  ),
  comments = "This class is generated by jOOQ"
)
class TmCombinationPart(
    private var id : Integer      
  , private var lotteryId : Integer      
  , private var partNumber : Short        
  , private var name : String       
  , private var numValues : Short        
  , private var created : LocalDateTime
  , private var modified : LocalDateTime
) extends Serializable {

  def this() = {
    this(null, null, null, null, null, null, null)
  }

  def this (value : TmCombinationPart) = {
    this(
        value.id
      , value.lotteryId
      , value.partNumber
      , value.name
      , value.numValues
      , value.created
      , value.modified
    )
  }

  def getId : Integer = {
    this.id
  }

  def setId(id : Integer) : Unit = {
    this.id = id
  }

  def getLotteryId : Integer = {
    this.lotteryId
  }

  def setLotteryId(lotteryId : Integer) : Unit = {
    this.lotteryId = lotteryId
  }

  def getPartNumber : Short = {
    this.partNumber
  }

  def setPartNumber(partNumber : Short) : Unit = {
    this.partNumber = partNumber
  }

  def getName : String = {
    this.name
  }

  def setName(name : String) : Unit = {
    this.name = name
  }

  def getNumValues : Short = {
    this.numValues
  }

  def setNumValues(numValues : Short) : Unit = {
    this.numValues = numValues
  }

  def getCreated : LocalDateTime = {
    this.created
  }

  def setCreated(created : LocalDateTime) : Unit = {
    this.created = created
  }

  def getModified : LocalDateTime = {
    this.modified
  }

  def setModified(modified : LocalDateTime) : Unit = {
    this.modified = modified
  }

  override def toString : String = {
    val sb = new StringBuilder("TmCombinationPart (")

    sb.append(id)
    sb.append(", ").append(lotteryId)
    sb.append(", ").append(partNumber)
    sb.append(", ").append(name)
    sb.append(", ").append(numValues)
    sb.append(", ").append(created)
    sb.append(", ").append(modified)

    sb.append(")");
    return sb.toString
  }
}
