/**
 * This class is generated by jOOQ
 */
package com.serinus.loto.model.pojos


import java.io.Serializable
import java.lang.Integer
import java.lang.String
import java.lang.StringBuilder
import java.time.LocalDate
import java.time.LocalDateTime

import javax.annotation.Generated

import scala.Array


/**
 * This class is generated by jOOQ.
 */
@Generated(
  value = Array(
    "http://www.jooq.org",
    "jOOQ version:3.8.6"
  ),
  comments = "This class is generated by jOOQ"
)
class TwResult(
    private var id : Integer      
  , private var raffleDay : LocalDate    
  , private var combinationPartId : Integer      
  , private var values : String       
  , private var created : LocalDateTime
) extends Serializable {

  def this() = {
    this(null, null, null, null, null)
  }

  def this (value : TwResult) = {
    this(
        value.id
      , value.raffleDay
      , value.combinationPartId
      , value.values
      , value.created
    )
  }

  def getId : Integer = {
    this.id
  }

  def setId(id : Integer) : Unit = {
    this.id = id
  }

  def getRaffleDay : LocalDate = {
    this.raffleDay
  }

  def setRaffleDay(raffleDay : LocalDate) : Unit = {
    this.raffleDay = raffleDay
  }

  def getCombinationPartId : Integer = {
    this.combinationPartId
  }

  def setCombinationPartId(combinationPartId : Integer) : Unit = {
    this.combinationPartId = combinationPartId
  }

  def getValues : String = {
    this.values
  }

  def setValues(values : String) : Unit = {
    this.values = values
  }

  def getCreated : LocalDateTime = {
    this.created
  }

  def setCreated(created : LocalDateTime) : Unit = {
    this.created = created
  }

  override def toString : String = {
    val sb = new StringBuilder("TwResult (")

    sb.append(id)
    sb.append(", ").append(raffleDay)
    sb.append(", ").append(combinationPartId)
    sb.append(", ").append(values)
    sb.append(", ").append(created)

    sb.append(")");
    return sb.toString
  }
}
